// Constants
ITEM_BREATH_START_SCALE = 1.0;
ITEM_BREATH_END_SCALE = 1.25;
ITEM_BREATH_INTERVAL = 3.0;
ITEM_BREATH_OFFSET = 0.0;
HIGHLIGHTED_RANGE = 75;
HIGHLIGHTED_COLOR = c_aqua;

// Variables
playerInVicinity = false;