// Constants
ITEM_BREATH_START_SCALE = 0.4;
ITEM_BREATH_END_SCALE = 0.55;
ITEM_BREATH_INTERVAL = 3.0;
ITEM_BREATH_OFFSET = 0.0;
HIGHLIGHTED_RANGE = 75;
HIGHLIGHTED_COLOR = c_red;

// Variables
playerInVicinity = false;